    name: GitHub Classroom Workflow

    on: 
      push:
        branches:
        - '*'
        - '!badges'

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

          - name: setup SQL Server instance
            run: docker run -v $(pwd):/app -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Pa$$w0rd1234' -p 1433:1433 --name sql2017 -d mcr.microsoft.com/mssql/server:2017-latest || sleep 10


          - name: create command shortcut variable
            run: DBCMD="docker exec sql2017 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Pa\$\$w0rd1234"

          # - name: run queries
          #   run: mssql -u sa -p Pa\$\$w0rd1234 .databases

          # add id to step so outputs can be referenced
          - uses: education/autograding@v1
            id: autograder
            continue-on-error: true
                        
          - name: check autograder pass fail
            if: ${{ steps.autograder.outcome != 'success' }}
            run: echo  ${{ steps.autograder.outcome.error}} || echo  ${{ steps.autograder.error}} || exit 1
